version: "3.9"
services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
